name: Build web
on:
  push:
    branches:
      - master
      - main
      - v5
      - v3
      - dev
      - own
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [15.9.0] #指定node版本
    steps:
    - name: Use Node.js ${{ matrix.node-version }} #使用action安装node环境
      uses: actions/setup-node@v1
      with:
        persist-credentials: false
        node-version: ${{ matrix.node-version }}
    - name: ssh scp ssh pipelines
      run: |
        npm install
        npm run build
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
